Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 1
    v.memory = 2048
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.define "emmodoglS" do |server|
    server.vm.hostname = "emmodoglS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "scripts/server_setup.sh"
  end

  config.vm.define "eatesSW" do |worker|
    worker.vm.hostname = "eatesSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "scripts/worker_setup.sh"
  end
end